version: "3"

output: prefixed

silent: true

env:
  CGO_ENABLED: '0'

vars:
  GIT_REV:
    sh: git rev-parse --short HEAD
  GIT_TAG:
    sh: git describe --tags --abbrev=0
  LDFLAGS: -s -w -X github.com/vaclav-dvorak/goit/cmd.version={{.GIT_TAG}}+{{.GIT_REV}}
  FILE: goit

tasks:
  prepare:
    desc: Download dependencies and prepare dev env
    cmds:
      - pre-commit install
      - go mod download
      - go mod tidy
      - go mod vendor

  build:
    desc: Builds the cli binary
    cmds:
      - go build -trimpath -ldflags="{{.LDFLAGS}}" -o ./bin/{{.FILE}} main.go

  build:ci:
    desc: Optimized build for CI
    cmds:
      - echo {{.GOOS}}/{{.GOARCH}}
      - go build -trimpath -ldflags="{{.LDFLAGS}}" -o ./{{.FILE}}{{.exeExt}} main.go
      - tar -czf {{.PACKAGE}}.tar.gz ./{{.FILE}}{{.exeExt}} ./LICENSE
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
      PACKAGE: "{{.FILE}}_{{.GOOS}}_{{.GOARCH}}"

  test:
    desc: Runs all tests
    cmds:
      - go test ./...

  clean:
    desc: Cleans temp files and folders
    cmds:
      - rm -rf bin/
      - rm -f *.tag.gz
